### ISSUE TITLE
Error with setup steps from README.md file (development branch)

### ISSUE THREAD

**Issue by sbsimo** [HaitiData/haitidata#144]
Are these steps still valid?
https://github.com/HaitiData/haitidata/blob/development/README.md

When running: 
`make deploy`
on Ubuntu 16.04  (docker version = 17.11.0-ce, build 1caf76c  AND docker-compose version 1.17.0, build ac53b73)
 
I get the following error stack trace

```
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 91, in handle
    connection.prepare_database()
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 36, in prepare_database
    if self.template_postgis is None:
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 28, in template_postgis
    with self._nodb_connection.cursor() as cursor:
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  no pg_hba.conf entry for host "172.18.0.4", user "docker", database "gis", SSL on
FATAL:  no pg_hba.conf entry for host "172.18.0.4", user "docker", database "gis", SSL off

Makefile:104: recipe for target 'migrate' failed
make: *** [migrate] Error 1

```

**Comment by dimasciput** [comment]
Hi @sbsimo , I fixed this issue here https://github.com/HaitiData/haitidata/pull/148. Now you can just do `make deploy`.

**Comment by sbsimo** [comment]
Hi @dimasciput ,
most of the times when running ```make deploy``` the setup process fails with issues on the db (mainly in the migrate command). 
I guess the reason is that it takes some more time for the db to be up and running, ins't it?

In fact if I run ```make deploy``` twice, the setup process ends smoothly the second time. I guess running ```make deploy``` twice does not produce any negative consequence, does it?

**Comment by dimasciput** [comment]
Hi @sbsimo, yes because there is a process to start the db and it takes some time. Maybe before make deploy we can run the `make db` to start the db first. Or like you said we can run the `make deploy` twice.

**Comment by cchristelis** [comment]
@sbsimo, could you confirm that you have this running and that we can close this issue?

**Comment by sbsimo** [comment]
@dimasciput thanks, now it's clear to me.
@cchristelis yes it is running, I'm closing it
