### ISSUE TITLE
Include GeoServer CSS plugin in deployment

### ISSUE THREAD

**Issue by ppasq** [HaitiData/haitidata#36]
The plugin was placed in [https://github.com/HaitiData/haitidata/tree/development/deployment/docker-geoserver/resources/plugins](https://github.com/HaitiData/haitidata/tree/development/deployment/docker-geoserver/resources/plugins) but it is not deployed.

**Comment by meomancer** [comment]
how to deploy this @ppasq ?

**Comment by ppasq** [comment]
Hi @meomancer 
The .jar files must be placed inside the geoserver/WEB-INF/lib/ folder. Tomcat must be restarted to enable the plugin. When creating a new style in GeoServer the label CSS will appear as an option in the format drop down menu (along with SLD and ZIP).

**Comment by meomancer** [comment]
hi @ppasq 
after i added plugins, the geoserver is error

here is on the lib:
```
root@c02c870ea491:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib# ls
GeographicLib-Java-1.44.jar                    gs-notification-geonode-2.10-SNAPSHOT.jar      hibernate-jpa-2.0-api-1.0.0.Final.jar  mail-1.4.jar
HikariCP-2.4.2.jar                             gs-ows-2.10-SNAPSHOT.jar                       hibernate-spatial-1.1.1.jar            mapfish-geo-lib-1.2.0.jar
JavaAPIforKml-2.2.0.jar                        gs-platform-2.10-SNAPSHOT.jar                  hibernate-spatial-h2-geodb-1.1.1.jar   maven-scm-api-1.4.jar
accessors-smart-1.1.jar                        gs-printing-2.10-SNAPSHOT.jar                  hsqldb-2.3.0.jar                       maven-scm-provider-svn-commons-1.4.jar
activation-1.1.jar                             gs-rest-2.10-SNAPSHOT.jar                      httpclient-4.5.1.jar                   maven-scm-provider-svnexe-1.4.jar
amqp-client-4.0.0.jar                          gs-restconfig-2.10-SNAPSHOT.jar                httpcore-4.4.4.jar                     metrics-core-3.0.2.jar
ant-1.6.5.jar                                  gs-sec-jdbc-2.10-SNAPSHOT.jar                  icu4j-3.4.4.jar                        metrics-healthchecks-3.0.2.jar
antlr-2.7.6.jar                                gs-sec-ldap-2.10-SNAPSHOT.jar                  imageio-ext-arcgrid-1.1.17.jar         metrics-httpclient-3.0.2.jar
aopalliance-1.0.jar                            gs-sec-oauth2-2.10-SNAPSHOT.jar                imageio-ext-geocore-1.1.17.jar         metrics-json-3.0.2.jar
asm-5.0.3.jar                                  gs-sec-oauth2-geonode-2.10-SNAPSHOT.jar        imageio-ext-png-1.1.17.jar             metrics-jvm-3.0.2.jar
asm-analysis-5.0.3.jar                         gs-wcs-2.10-SNAPSHOT.jar                       imageio-ext-streams-1.1.17.jar         metrics-log4j-3.0.2.jar
asm-tree-5.0.3.jar                             gs-wcs1_0-2.10-SNAPSHOT.jar                    imageio-ext-tiff-1.1.17.jar            metrics-servlet-3.0.2.jar
asm-util-5.0.3.jar                             gs-wcs1_1-2.10-SNAPSHOT.jar                    imageio-ext-utilities-1.1.17.jar       metrics-servlets-3.0.2.jar
aspectjrt-1.5.4.jar                            gs-wcs2_0-2.10-SNAPSHOT.jar                    itext-2.1.5.jar                        net.opengis.fes-16-SNAPSHOT.jar
aspectjweaver-1.5.4.jar                        gs-web-core-2.10-SNAPSHOT.jar                  itextpdf-5.4.4.jar                     net.opengis.ows-16-SNAPSHOT.jar
avalon-framework-api-4.3.1.jar                 gs-web-demo-2.10-SNAPSHOT.jar                  jackson-annotations-2.3.2.jar          net.opengis.wcs-16-SNAPSHOT.jar
avalon-framework-impl-4.3.1.jar                gs-web-gwc-2.10-SNAPSHOT.jar                   jackson-core-2.3.2.jar                 net.opengis.wfs-16-SNAPSHOT.jar
batik-anim-1.7.jar                             gs-web-rest-2.10-SNAPSHOT.jar                  jackson-core-asl-1.9.13.jar            net.opengis.wps-16-SNAPSHOT.jar
batik-awt-util-1.7.jar                         gs-web-sec-core-2.10-SNAPSHOT.jar              jackson-databind-2.3.2.jar             objenesis-1.2.jar
batik-bridge-1.7.jar                           gs-web-sec-jdbc-2.10-SNAPSHOT.jar              jackson-mapper-asl-1.9.13.jar          org.eclipse.jdt.annotation-1.1.0.jar
batik-css-1.7.jar                              gs-web-sec-ldap-2.10-SNAPSHOT.jar              jai_codec-1.1.3.jar                    org.json-2.0.jar
batik-dom-1.7.jar                              gs-web-wcs-2.10-SNAPSHOT.jar                   jai_core-1.1.3.jar                     org.restlet-1.0.8-noobjrep.jar
batik-ext-1.7.jar                              gs-web-wfs-2.10-SNAPSHOT.jar                   jai_imageio-1.1.jar                    org.restlet-1.0.8.jar
batik-gvt-1.7.jar                              gs-web-wms-2.10-SNAPSHOT.jar                   jansi-1.11.jar                         org.restlet.ext.fileupload-1.0.8.jar
batik-js-1.7.jar                               gs-web-wps-2.10-SNAPSHOT.jar                   jasper-compiler-5.5.15.jar             org.restlet.ext.freemarker-1.0.8.jar
batik-parser-1.7.jar                           gs-wfs-2.10-SNAPSHOT.jar                       jasper-compiler-jdt-5.5.15.jar         org.restlet.ext.json-1.0.8.jar
batik-script-1.7.jar                           gs-wms-2.10-SNAPSHOT.jar                       jasper-runtime-5.5.15.jar              org.restlet.ext.spring-1.0.8.jar
batik-svg-dom-1.7.jar                          gs-wps-core-2.10-SNAPSHOT.jar                  jasypt-1.8.jar                         org.simpleframework-3.1.3.jar
batik-svggen-1.7.jar                           gson-2.4.jar                                   javacsv-2.0.jar                        org.w3.xlink-16-SNAPSHOT.jar
batik-transcoder-1.7.jar                       gt-api-16-SNAPSHOT.jar                         javassist-3.12.0.GA.jar                parboiled-core-1.1.7.jar
batik-util-1.7.jar                             gt-app-schema-resolver-16-SNAPSHOT.jar         javax.batch-api-1.0.jar                parboiled-java-1.1.7.jar
batik-xml-1.7.jar                              gt-arcgrid-16-SNAPSHOT.jar                     javax.inject-1.jar                     pdfbox-1.6.0.jar
bcmail-jdk14-138.jar                           gt-arcsde-16-SNAPSHOT.jar                      javax.json-1.0.4.jar                   picocontainer-1.2.jar
bcprov-jdk14-138.jar                           gt-arcsde-common-16-SNAPSHOT.jar               javax.servlet-api-3.1.0.jar            plexus-utils-1.5.6.jar
bcprov-jdk15on-1.54.jar                        gt-brewer-16-SNAPSHOT.jar                      jcommander-1.48.jar                    pngj-2.0.1.jar
cglib-nodep-2.2.jar                            gt-complex-16-SNAPSHOT.jar                     jdom-1.1.3.jar                         poi-3.14.jar
com.ibm.jbatch-tck-spi-1.0.jar                 gt-coverage-16-SNAPSHOT.jar                    jempbox-1.6.0.jar                      poi-ooxml-3.14.jar
com.noelios.restlet-1.0.8.jar                  gt-cql-16-SNAPSHOT.jar                         jettison-1.0.1.jar                     poi-ooxml-schemas-3.14.jar
com.noelios.restlet.ext.servlet-1.0.8.jar      gt-css-16-SNAPSHOT.jar                         jetty-http-9.2.13.v20150730.jar        postgis-jdbc-1.3.3.jar
com.noelios.restlet.ext.simple-1.0.8.jar       gt-csv-16-SNAPSHOT.jar                         jetty-io-9.2.13.v20150730.jar          postgresql-42.1.1.jar
common-2.6.0.jar                               gt-data-16-SNAPSHOT.jar                        jetty-jndi-9.2.13.v20150730.jar        postgresql-8.4-702.jdbc3.jar
commons-beanutils-1.7.0.jar                    gt-epsg-hsql-16-SNAPSHOT.jar                   jetty-plus-9.2.13.v20150730.jar        prettytime-1.0.8.Final.jar
commons-beanutils-1.9.2-noclassprop.jar        gt-geojson-16-SNAPSHOT.jar                     jetty-security-9.2.13.v20150730.jar    print-lib-2.1.2.jar
commons-codec-1.9.jar                          gt-geopkg-16-SNAPSHOT.jar                      jetty-server-9.2.13.v20150730.jar      printng-2.9.0.jar
commons-collections-3.2.2.jar                  gt-geotiff-16-SNAPSHOT.jar                     jetty-servlet-9.2.13.v20150730.jar     regexp-1.3.jar
commons-dbcp-1.4.jar                           gt-graph-16-SNAPSHOT.jar                       jetty-util-9.2.13.v20150730.jar        rocksdbjni-4.13.4.jar
commons-digester-1.7.jar                       gt-grid-16-SNAPSHOT.jar                        jetty-webapp-9.2.13.v20150730.jar      search-1.1.0.jar
commons-el-1.0.jar                             gt-gtopo30-16-SNAPSHOT.jar                     jetty-xml-9.2.13.v20150730.jar         search-hibernate-1.1.0.jar
commons-exec-1.3.jar                           gt-image-16-SNAPSHOT.jar                       jgridshift-1.0.jar                     search-jpa-hibernate-1.1.0.jar
commons-fileupload-1.2.1.jar                   gt-imagemosaic-16-SNAPSHOT.jar                 json-20080701.jar                      serializer-2.7.1.jar
commons-httpclient-3.1.jar                     gt-jdbc-16-SNAPSHOT.jar                        json-lib-2.2.3-jdk15.jar               servlet-api-2.4.jar
commons-io-2.1.jar                             gt-jdbc-h2-16-SNAPSHOT.jar                     json-path-2.2.0.jar                    slf4j-api-1.6.1.jar
commons-jxpath-1.3.jar                         gt-jdbc-oracle-16-SNAPSHOT.jar                 json-simple-1.1.jar                    slf4j-log4j12-1.6.4.jar
commons-lang-2.6.jar                           gt-jdbc-postgis-16-SNAPSHOT.jar                json-smart-2.2.1.jar                   spatialite-jdbc-3.7.2-2.4.jar
commons-logging-1.1.1.jar                      gt-jdbc-spatialite-16-SNAPSHOT.jar             jsp-api-2.0.jar                        spring-aop-4.2.5.RELEASE.jar
commons-pool-1.5.4.jar                         gt-jdbc-sqlserver-16-SNAPSHOT.jar              jsqlparser-0.3.14.jar                  spring-batch-core-3.0.7.RELEASE.jar
commons-validator-1.1.4.jar                    gt-main-16-SNAPSHOT.jar                        jsr-275-1.0-beta-2.jar                 spring-batch-infrastructure-3.0.7.RELEASE.jar
commons-vfs2-2.0.jar                           gt-metadata-16-SNAPSHOT.jar                    jsr305-2.0.3.jar                       spring-batch-integration-3.0.7.RELEASE.jar
compress-lzf-1.0.3.jar                         gt-opengis-16-SNAPSHOT.jar                     jt-affine-1.0.13.jar                   spring-batch-test-3.0.7.RELEASE.jar
core-0.26.jar                                  gt-process-16-SNAPSHOT.jar                     jt-algebra-1.0.13.jar                  spring-beans-4.2.5.RELEASE.jar
core-3.1.1.jar                                 gt-process-feature-16-SNAPSHOT.jar             jt-attributeop-1.4.0.jar               spring-context-4.2.5.RELEASE.jar
core-renderer-R8-SNAPSHOT.jar                  gt-process-geometry-16-SNAPSHOT.jar            jt-bandcombine-1.0.13.jar              spring-context-support-4.2.5.RELEASE.jar
curvesapi-1.03.jar                             gt-process-raster-16-SNAPSHOT.jar              jt-bandmerge-1.0.13.jar                spring-core-4.2.5.RELEASE.jar
dao-1.1.0.jar                                  gt-property-16-SNAPSHOT.jar                    jt-bandselect-1.0.13.jar               spring-expression-4.2.5.RELEASE.jar
dom4j-1.6.1.jar                                gt-referencing-16-SNAPSHOT.jar                 jt-binarize-1.0.13.jar                 spring-integration-core-4.2.5.RELEASE.jar
easymockclassextension-2.5.2.jar               gt-render-16-SNAPSHOT.jar                      jt-border-1.0.13.jar                   spring-jdbc-4.2.5.RELEASE.jar
ecore-2.6.1.jar                                gt-shapefile-16-SNAPSHOT.jar                   jt-buffer-1.0.13.jar                   spring-jms-4.2.5.RELEASE.jar
ehcache-1.6.2.jar                              gt-svg-16-SNAPSHOT.jar                         jt-classifier-1.0.13.jar               spring-ldap-core-2.0.2.RELEASE.jar
encoder-1.1.jar                                gt-transform-16-SNAPSHOT.jar                   jt-colorconvert-1.0.13.jar             spring-messaging-4.2.5.RELEASE.jar
ezmorph-1.0.6.jar                              gt-wfs-ng-16-SNAPSHOT.jar                      jt-colorindexer-1.0.13.jar             spring-orm-4.2.5.RELEASE.jar
fontbox-1.6.0.jar                              gt-wms-16-SNAPSHOT.jar                         jt-concurrent-tile-cache-1.0.13.jar    spring-oxm-3.0.5.RELEASE.jar
fop-0.94.jar                                   gt-xml-16-SNAPSHOT.jar                         jt-contour-1.4.0.jar                   spring-retry-1.1.2.RELEASE.jar
freemarker-2.3.18.jar                          gt-xsd-core-16-SNAPSHOT.jar                    jt-crop-1.0.13.jar                     spring-security-config-4.0.4.RELEASE.jar
geodb-0.7-RC2.jar                              gt-xsd-fes-16-SNAPSHOT.jar                     jt-errordiffusion-1.0.13.jar           spring-security-core-4.0.4.RELEASE.jar
geofence-model-internal-3.2-SNAPSHOT.jar       gt-xsd-filter-16-SNAPSHOT.jar                  jt-format-1.0.13.jar                   spring-security-ldap-4.0.4.RELEASE.jar
geofence-persistence-3.2-SNAPSHOT.jar          gt-xsd-gml2-16-SNAPSHOT.jar                    jt-imagefunction-1.0.13.jar            spring-security-oauth2-2.0.11.RELEASE.jar
geofence-services-api-3.2-SNAPSHOT.jar         gt-xsd-gml3-16-SNAPSHOT.jar                    jt-iterators-1.0.13.jar                spring-security-web-4.0.4.RELEASE.jar
geofence-services-impl-3.2-SNAPSHOT.jar        gt-xsd-kml-16-SNAPSHOT.jar                     jt-lookup-1.0.13.jar                   spring-test-4.2.5.RELEASE.jar
geogig-api-1.1-SNAPSHOT.jar                    gt-xsd-ows-16-SNAPSHOT.jar                     jt-mosaic-1.0.13.jar                   spring-tx-4.2.5.RELEASE.jar
geogig-cli-1.1-SNAPSHOT.jar                    gt-xsd-sld-16-SNAPSHOT.jar                     jt-nullop-1.0.13.jar                   spring-web-4.2.5.RELEASE.jar
geogig-core-1.1-SNAPSHOT.jar                   gt-xsd-wcs-16-SNAPSHOT.jar                     jt-orderdither-1.0.13.jar              spring-webmvc-4.2.5.RELEASE.jar
geogig-datastore-1.1-SNAPSHOT.jar              gt-xsd-wfs-16-SNAPSHOT.jar                     jt-piecewise-1.0.13.jar                sqlite-jdbc-3.14.2.1.jar
geogig-geotools-1.1-SNAPSHOT.jar               gt-xsd-wps-16-SNAPSHOT.jar                     jt-rangelookup-1.4.0.jar               stax-1.2.0.jar
geogig-postgres-1.1-SNAPSHOT.jar               guava-17.0.jar                                 jt-rescale-1.0.13.jar                  stax-api-1.0.1.jar
geogig-rocksdb-1.1-SNAPSHOT.jar                guice-4.0-no_aop.jar                           jt-rlookup-1.0.13.jar                  tagsoup-1.2.1.jar
geogig-web-api-1.1-SNAPSHOT.jar                guice-multibindings-4.0.jar                    jt-scale-1.0.13.jar                    wicket-core-7.1.0.jar
gs-authkey-2.10-SNAPSHOT.jar                   gwc-core-1.10-SNAPSHOT.jar                     jt-stats-1.0.13.jar                    wicket-dnd-0.7.3.jar
gs-backup-restore-core-2.10-SNAPSHOT.jar       gwc-diskquota-core-1.10-SNAPSHOT.jar           jt-translate-1.0.13.jar                wicket-extensions-7.1.0.jar
gs-backup-restore-extension-2.10-SNAPSHOT.jar  gwc-diskquota-jdbc-1.10-SNAPSHOT.jar           jt-utilities-1.0.13.jar                wicket-request-7.1.0.jar
gs-backup-restore-rest-2.10-SNAPSHOT.jar       gwc-georss-1.10-SNAPSHOT.jar                   jt-utils-1.4.0.jar                     wicket-util-7.1.0.jar
gs-backup-restore-web-2.10-SNAPSHOT.jar        gwc-gmaps-1.10-SNAPSHOT.jar                    jt-vectorbin-1.0.13.jar                xalan-2.7.0.jar
gs-css-2.10-SNAPSHOT.jar                       gwc-kml-1.10-SNAPSHOT.jar                      jt-vectorbinarize-1.4.0.jar            xercesImpl-2.11.0.jar
gs-excel-2.10-SNAPSHOT.jar                     gwc-rest-1.10-SNAPSHOT.jar                     jt-vectorize-1.4.0.jar                 xml-apis-1.4.01.jar
gs-geofence-2.10-SNAPSHOT.jar                  gwc-tms-1.10-SNAPSHOT.jar                      jt-warp-1.0.13.jar                     xml-apis-ext-1.3.04.jar
gs-geofence-server-2.10-SNAPSHOT.jar           gwc-ve-1.10-SNAPSHOT.jar                       jt-zonal-1.0.13.jar                    xml-apis-xerces-2.7.1.jar
gs-geogig-2.10-SNAPSHOT.jar                    gwc-wms-1.10-SNAPSHOT.jar                      jt-zonalstats-1.4.0.jar                xml-commons-resolver-1.2.jar
gs-gwc-2.10-SNAPSHOT.jar                       gwc-wmts-1.10-SNAPSHOT.jar                     jta-1.1.jar                            xmlbeans-2.6.0.jar
gs-h2-2.10-SNAPSHOT.jar                        h2-1.1.119.jar                                 jtds-1.3.1.jar                         xmlgraphics-commons-1.2.jar
gs-importer-core-2.10-SNAPSHOT.jar             hamcrest-core-1.3.jar                          jts-1.13.jar                           xmlpull-1.1.3.1.jar
gs-importer-rest-2.10-SNAPSHOT.jar             hamcrest-library-1.3.jar                       jyaml-1.3.jar                          xpp3-1.1.3.4.O.jar
gs-importer-web-2.10-SNAPSHOT.jar              hatbox-1.0.b7.jar                              log4j-1.2.17.jar                       xpp3_min-1.1.4c.jar
gs-kml-2.10-SNAPSHOT.jar                       hibernate-commons-annotations-3.2.0.Final.jar  log4j-api-2.0.2.jar                    xsd-2.6.0.jar
gs-main-2.10-SNAPSHOT.jar                      hibernate-core-3.6.0.Final.jar                 logback-classic-1.1.2.jar              xstream-1.4.10.jar
gs-notification-2.10-SNAPSHOT.jar              hibernate-ehcache-3.6.0.Final.jar              logback-core-1.1.2.jar
gs-notification-common-2.10-SNAPSHOT.jar       hibernate-entitymanager-3.6.0.Final.jar        lz4-1.3.0.jar
```
i see all file in plugins zip are there

here is the error
```
11-Oct-2017 03:58:51.690 SEVERE [main] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/geoserver]]
        at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:441)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:740)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:716)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1134)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1868)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1045)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:433)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1578)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:964)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1425)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1415)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:941)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:657)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)
Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/geoserver] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1EncodableVector->org.bouncycastle.asn1.DEREncodableVector->org.bouncycastle.asn1.ASN1EncodableVector]
        at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2112)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2056)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2002)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1972)
        at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1925)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1163)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:775)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4993)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        ... 38 more

11-Oct-2017 03:58:51.692 SEVERE [main] org.apache.catalina.startup.HostConfig.deployDirectory Error deploying web application directory [/usr/local/tomcat/webapps/geoserver]
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/geoserver]]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:744)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:716)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1134)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1868)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1045)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:433)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1578)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:964)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1425)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1415)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:941)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:657)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)
```
have you encountered this before?

**Comment by cchristelis** [comment]
@meomancer and @ppasq are there any updates here?

**Comment by ppasq** [comment]
Which GeoServer version are you using, 2.10 or 2.9? Plugins must match GeoServer version.

**Comment by cchristelis** [comment]
2.10 @ppasq

**Comment by meomancer** [comment]
hi @ppasq 
after i check it, "parboiled-core-1.1.7.jar" and "parboiled-java-1.1.7.jar" break the geoserver

**Comment by meomancer** [comment]
hi @ppasq 
it is loaded now : PR https://github.com/HaitiData/haitidata/pull/83
i was recreate the geoserver and reload geoserver from tomcat
it is loaded
